# Generated by Django 2.2.2 on 2019-08-04 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_budget_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='remind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pay', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, max_length=100)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
