# Generated by Django 2.2.2 on 2019-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
